image:
  repository: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efa-k8s-device-plugin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.3.3"
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

supportedInstanceLabels: # EFA supported instances: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-instance-types
  keys:
    - "beta.kubernetes.io/instance-type"
    - "node.kubernetes.io/instance-type"
  values:
    - m5dn.24xlarge
    - m5dn.metal
    - m5n.24xlarge
    - m5n.metal
    - m5zn.12xlarge
    - m5zn.metal
    - m6a.32xlarge
    - m6a.48xlarge
    - m6a.metal
    - m6i.32xlarge
    - m6i.metal
    - m6id.32xlarge
    - m6id.metal
    - c5n.18xlarge
    - c5n.9xlarge
    - c5n.metal
    - c6a.32xlarge
    - c6a.48xlarge
    - c6a.metal
    - c6gn.16xlarge
    - c6i.32xlarge
    - c6i.metal
    - c6id.32xlarge
    - c6id.metal
    - hpc6a.48xlarge
    - r5dn.24xlarge
    - r5dn.metal
    - r5n.24xlarge
    - r5n.metal
    - r6i.32xlarge
    - r6i.metal
    - r6id.32xlarge
    - r6id.metal
    - x2d.32xlarge
    - x2d.metal
    - x2ed.32xlarge
    - x2ed.metal
    - x2iezn.12xlarge
    - x2iezn.metal
    - x2idn.32xlarge
    - x2iedn.32xlarge
    - i3en.24xlarge
    - i3en.12xlarge
    - i3en.metal
    - i4i.32xlarge
    - i4i.metal
    - im4gn.16xlarge
    - dl1.24xlarge
    - g4dn.8xlarge
    - g4dn.12xlarge
    - g4dn.metal
    - g5.48xlarge
    - inf1.24xlarge
    - p3dn.24xlarge
    - p4d.24xlarge
    - p4de.24xlarge
    - trn1.32xlarge
    - trn1n.32xlarge

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
nodeSelector: {}
#  efa: present

additionalPodAnnotations: {}
additionalPodLabels: {}
nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

tolerations:
  - operator: Exists    # DaemonSet is tolerant of any taints, regardless of the key or value of the taint.
  - key: CriticalAddonsOnly
    operator: Exists
