apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-spark-access
  namespace: spark-team-a
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications"]
  verbs: ["get", "list", "put", "create", "delete", "patch", "watch"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications/status"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-spark-access-binding
  namespace: spark-team-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-spark-access
subjects:
- kind: ServiceAccount
  name: airflow-worker
  namespace: airflow
