apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: data-on-eks
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.9.1
    metadataVersion: 3.9.1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: locahost
        port: 9094
        type: internal
        tls: false
        configuration:
          advertisedHostTemplate: localhost
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    resources:
      requests:
        memory: 58Gi
        cpu: "6"
      limits:
        memory: 64Gi
        cpu: "8"
    jvmOptions:
      "-Xmx": "6g"
      "-Xms": "4g"
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: NodeGroupType
                      operator: In
                      values:
                        - general-purpose
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                        - arm64
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: "strimzi.io/pool-name"
                  operator: In
                  values:
                  - broker
                  - controller
              topologyKey: "kubernetes.io/hostname"
        topologySpreadConstraints:
          - labelSelector:
              matchExpressions:
              - key: "strimzi.io/pool-name"
                operator: In
                values:
                  - broker
                  - controller
            maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    rack:
      topologyKey: topology.kubernetes.io/zone
  entityOperator:
    topicOperator: {}
    userOperator: {}
  cruiseControl: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
