---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: cat-interactions
  namespace: kafka
  labels:
    strimzi.io/cluster: data-on-eks
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: visitor-checkins
  namespace: kafka
  labels:
    strimzi.io/cluster: data-on-eks
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: cafe-orders
  namespace: kafka
  labels:
    strimzi.io/cluster: data-on-eks
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: cat-wellness-iot
  namespace: kafka
  labels:
    strimzi.io/cluster: data-on-eks
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: cat-locations
  namespace: kafka
  labels:
    strimzi.io/cluster: data-on-eks
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: cat-health-alerts
  namespace: kafka
  labels:
    strimzi.io/cluster: data-on-eks
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: potential-adopters
  namespace: kafka
  labels:
    strimzi.io/cluster: data-on-eks
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
