apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-test
  namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-task-result-creator
  namespace: argo-workflows
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-test-wft-creator-binding
  namespace: argo-workflows
subjects:
- kind: ServiceAccount
  name: spark-test
roleRef:
  kind: Role
  name: workflow-task-result-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-application-manager
  namespace: spark-team-a
rules:
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-spark-manager
  namespace: spark-team-a
subjects:
- kind: ServiceAccount
  name: spark-test
  namespace: argo-workflows
roleRef:
  kind: Role
  name: spark-application-manager
  apiGroup: rbac.authorization.k8s.io
