
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sqs-spark-workflow
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: aws-sqs
      eventName: sqs-spark-workflow
  triggers:
    - template:
        name: sqs-spark-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: sqs-spark-workflow-
                namespace: argo-workflows
              spec:
                arguments: {}
                entrypoint: parallel-jobs
                serviceAccountName: spark-test
                templates:
                  - name: parallel-jobs
                    steps:
                      - - name: data-prep-1
                          templateRef:
                            name: wait
                            template: wait
                          arguments:
                            parameters:
                            - name: duration
                              value: '10'
                      - - name: spark-operator-pi-job
                          templateRef:
                            name: submit-spark-pi-app
                            template: spark-pi-app
                        - name: data-prep-2
                          templateRef:
                            name: wait
                            template: wait
                          arguments:
                            parameters:
                            - name: duration
                              value: '10'
                      - - name: spark-operator-taxi-job
                          templateRef:
                            name: submit-spark-pi-app
                            template: spark-taxi-app
