server:
  retention: 1h
  remoteWrite:
    - queue_config:
        max_samples_per_send: 1000
        max_shards: 200
        capacity: 2500
  global:
    evaluation_interval: 30s
    scrape_interval: 30s
    scrape_timeout: 10s

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

  persistentVolume:
    accessModes:
      - ReadWriteOnce
    enabled: true
    mountPath: /data
    size: 20Gi
    storageClass: gp2

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

# Additional scrape config for KubeCost
extraScrapeConfigs: |
  - job_name: kubecost
    honor_labels: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    dns_sd_configs:
      - names:
          - kubecost-cost-analyzer.kubecost.svc
        type: 'A'
        port: 9003
